name: Sync Fork

on:
  schedule:
    - cron: '*/1 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: SvininEvgeniy
          base: master
          head: master
          auto_approve: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
